### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zanebliss** [ZaneBliss/plaintext-notion#1]
- [x] Parse markdown for (some) content block types [e5c8f13](https://github.com/ZaneBliss/plaintext-notion/commit/e5c8f133027b12719523050a9fb275e164a1781e)
- [ ] Add support for `- [ ]` todos
- [ ] Parse markdown for rich content blocks
- [ ] Nested folders/pages
- [ ] Update already synced folders/files
- [ ] Metadata
- [ ] Background process for syncing
- [ ] Exclude test folders from rubocop without affecting entire project
